# CREATE_CUSTOMER = 'CREATE_CUSTOMER'
# VIEW_CUSTOMER = 'VIEW_CUSTOMER'
# UPDATE_CUSTOMER = 'UPDATE_CUSTOMER'

# CREATE_TICKET = 'CREATE_TICKET'
# VIEW_TICKET = 'VIEW_TICKET'
# UPDATE_TICKET_STATUS = 'UPDATE_TICKET_STATUS'
# UPDATE_TICKET_PRIORITY = 'UPDATE_TICKET_PRIORITY'
# CLOSE_TICKET = 'CLOSE_TICKET'
# REOPEN_TICKET = 'REOPEN_TICKET'

# VIEW_DASHBOARD_BASICS = 'VIEW_DASHBOARD_BASICS'
# VIEW_DASHBOARD_ADVANCED = 'VIEW_DASHBOARD_ADVANCED'

# DELETE_CUSTOMER = 'DELETE_CUSTOMER'
# DELETE_TICKET = 'DELETE_TICKET'
# MANAGE_USERS = 'MANAGE_USERS'

# ROLE_PERMISSIONS = {

#     "AGENT": {
#         CREATE_CUSTOMER,
#         VIEW_CUSTOMER,
#         UPDATE_CUSTOMER,
#         CREATE_TICKET,
#         VIEW_TICKET,
#         UPDATE_TICKET_STATUS,
        
        
#     }



# }